###############################################################################
# Tap Repositories                                                            #
###############################################################################

tap "caskroom/cask"
tap "caskroom/versions"


###############################################################################
# Install Casks                                                               #
###############################################################################

cask "brackets"
cask "blockblock"
cask "deluge"
cask "eclipse-java"
cask "firefox"
cask "github-desktop"
cask "java"
cask "iina"
cask "microsoft-office"
cask "oversight"
cask "purevpn"
cask "provisionql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "ransomwhere"
cask "spotify"
cask "steam"
cask "suspicious-package"
cask "teamspeak-client"
cask "teamviewer"
cask "telegram"
cask "the-unarchiver"
cask "xquartz"
